# Generated by Django 5.1.6 on 2025-02-21 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlecredentials',
            options={'verbose_name_plural': 'Google credentials'},
        ),
        migrations.RemoveField(
            model_name='googlecredentials',
            name='expiry',
        ),
        migrations.AlterField(
            model_name='googlecredentials',
            name='client_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='googlecredentials',
            name='client_secret',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='googlecredentials',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlecredentials',
            name='scopes',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='googlecredentials',
            name='token_uri',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='googlecredentials',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_credentials', to=settings.AUTH_USER_MODEL),
        ),
    ]
