# Generated by Django 5.1.6 on 2025-02-21 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_googlecredentials_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlecredentials',
            options={'verbose_name': 'Google Credential', 'verbose_name_plural': 'Google Credentials'},
        ),
    ]
