# Generated by Django 5.1.6 on 2025-03-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecredentials',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
